CREATE TABLE dbo.fastsel_tbl (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(150) NOT NULL,
    PhoneNumber NVARCHAR(50) NOT NULL,
    PropertyAddress NVARCHAR(255) NOT NULL,
    SpecificRequests NVARCHAR(MAX) NULL,
    SubmitDate DATETIME NOT NULL DEFAULT(GETDATE()),
    SellerIP VARCHAR(100) NULL
);
